### ISSUE TITLE
All moves highlighted and scoresheet shows all variations together when opening study moves

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#716] opened 2023-09-20 09:59 UTC
When using the "Download games from website" feature and then creating a repertoire chapter, opening the study moves, study 
window highlights all of the moves and the scoresheet shows all variations together. 

I am not sure if this is intended behavior or a bug.

![Screenshot (407)](https://github.com/czbar/ChessForge/assets/125844120/6ea6fe5b-0ca4-4cfe-b2fa-2e9b91e4dcbc)

**Comment by akaKarthick** [comment] 2023-09-20 10:00
ver 1.3.1

**Comment by czbar** [comment] 2023-09-20 15:34
Yes, I noticed that a few days ago and it is fixed in the next version.

This is one of the "unexpected" issues that unfortunately can happen in a major refactor.  This particular one was happening when you were opening a view before the background parallel reading finished. The program was "jumping the queue" to load the requested item immediately but then wasn't protecting against the background process overwriting it later on (and not preparing for display properly because it was marked as "ready" from that first load).  I have now put a triple safeguard against this happening again :)   Fixed in the upcoming version 1.3.2

**Comment by akaKarthick** [comment] 2023-09-21 10:52
I know you're busy, but I would really appreciate it if you could prioritize this release.

**Comment by czbar** [comment] 2023-09-21 16:25
Oh, and I guess you would have noticed.  The "workaround", of course, is to close and reopen the workbook.

**Comment by czbar** [comment] 2023-09-21 16:46
Ok, I hope I have finally woken up :)  What I explained above is complete nonsense. The bug was elsewhere. I have fixed it and placed build 1.3.2 in the usual place https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi  Bear in mind that this is a rushed release without any testing of the new features (like blunder detection, Copy/Move games/exercises  from the Identical Positions dialog or the Tools menu. Also, there are still issues with the background loading that I am looking into.

Anyway, hope this is useful to you, and I will upload a new, better tested build (1.3.3) in a few days

**Comment by akaKarthick** [comment] 2023-09-21 17:39
thank you for this release. Currently looking for bugs.

**Comment by akaKarthick** [comment] 2023-09-21 19:11
![Screenshot (411)](https://github.com/czbar/ChessForge/assets/125844120/c4198c34-8e8c-4ace-a6ab-9ac02a439773)

![Screenshot (404)](https://github.com/czbar/ChessForge/assets/125844120/fe99da95-f902-4de0-a7f4-1793c88b0d02)

**Comment by czbar** [comment] 2023-09-21 20:51
Great report, thanks! I will look into these in more detail later on.  My quick comments for now: 

Re 1: Can't repro on my machine.  As implemented now, changing fonts and indents are internal to the RichTextBox and I have no control over that. However, I can change the implementation and do it in my code "by hand" rather than relying on Microsoft :)   If this crashes for you, it will crash on other machines too, even if it does not crash on mine.  If I do my own implementation, then I can certainly prevent crashes. 

Re 2: This is by design ... meaning, I never implemented it.  Something to consider, I guess.

Re 3: Yeah, the Intro implementation is tricky and difficult. I'll see what I can do.

Re 4,5: I can repro so I can fix it.  It's quite funny, though :)

Re 6: It comes from the system clipboard where I place a textual representation of moves and diagrams. So that you can paste this in Notepad and such.  However, when pasting back in ChessForge, I check if I should paste the text from the system clipboard or actual ChessForge objects from the program's clipboard.  This check fails here.  Do you remember if you did anything particular between Copy and Paste?  Something fooled my check logic.

Re 7: Reproduced and will fix it.

Re 8: Can't repro but see my comment Re 1.

Re 9: I haven't looked into this yet.

Re 10: Yes, same as item 7 (and the same underlying reason in the code)

Re 11: Is this a bug or is the game indeed empty?  If you open the game on lichess, are there any moves there? This happens quite a lot. Maybe I should check the dialog so it does not look like this is a ChessForge error.  I'll show the lichess logo with a red cross on it instead :)

**Comment by akaKarthick** [comment] 2023-09-22 03:41
Re1.  i meant this 
![Screenshot (411)](https://github.com/czbar/ChessForge/assets/125844120/de4d8176-fa9b-456f-b673-c714653865f0)

Re6,8. I dont remember the way. i also cant repro.

**Comment by czbar** [comment] 2023-09-23 01:35
I have opened #725 and #726 based one the remaining issues since this item was originally opened for a different purpose.

For this one, please verify if the original issue was fixed, for the two new ones, feel free to edit or add to them.

**Closed** 2023-09-23 10:25 UTC
Labels: fixed
