### ISSUE TITLE
+ Symbol Not Displayed for Check

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#619] opened 2023-07-10 13:56 UTC
When I played the move "18.Nd6+" on chess.com, the + symbol was displayed to indicate that the move puts my opponent in check. 

![Screenshot (277)](https://github.com/czbar/ChessForge/assets/125844120/e00d373b-39b4-4bdc-9c31-d4f078c809aa)

However, when I played the same move in ChessForge, the + symbol was not displayed.

![Screenshot (280)](https://github.com/czbar/ChessForge/assets/125844120/f6060341-bec5-406e-bf50-c56591bef711)

**Comment by czbar** [comment] 2023-07-10 18:25
Currently, not displaying the check symbol in the "engine lines box" is by design to help with performance (the engine does not say it is a check so ChessForge would need to verify it itself for each displayed move). I may try it and see if it is a big performance hit. If it proves not too bad, I may add it.

**Comment by czbar** [comment] 2023-07-16 08:52
Fixed in 1.1.4 available from https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi

**Closed** 2023-07-16 10:42 UTC
Labels: fixed
