### ISSUE TITLE
Create an exercise from here

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#610] opened 2023-06-29 18:51 UTC
"Create an exercise from here" on the scoresheet creates an initial position.

https://github.com/czbar/ChessForge/assets/125844120/464a2580-f943-4c89-86b6-b54c740a1916

**Comment by czbar** [comment] 2023-07-11 20:40
The bug was caused by the program relying on the last view in focus. If the game view was not clicked before creating an exercise from the scoresheet, the last focus was on the Study and the Exercise was created from the study's selected move i.e. the starting position. This is fixed now (next version that will be published),

In addition, while at it, I have changed the content of the exercise header when created from the study, to something more elegant (namely, chapter name as "White", and move number as "Black":

![image](https://github.com/czbar/ChessForge/assets/7270924/8c881358-69e1-40d1-87f4-4c9badceb8aa)

**Closed** 2023-07-13 16:03 UTC
Labels: fixed
