### ISSUE TITLE
Scoresheet bug in Study tab

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#656] opened 2023-08-09 02:56 UTC
https://youtu.be/gmRSOVaryg4
https://youtu.be/GLhW0fGQ4RA
https://youtu.be/IIjFgRyKL8w

**Comment by akaKarthick** [comment] 2023-08-09 05:27
https://youtu.be/ywN49UOPbg4

**Comment by akaKarthick** [comment] 2023-08-09 19:05
> Can you please attach your Endgame.pgn file so I can hopefully reproduce it?
You mean this? https://drive.google.com/drive/folders/1HzGE9TKIuVT76WURbePtbtp2dDcz4OUi?usp=sharing

**Comment by czbar** [comment] 2023-08-09 23:43
No, I mean the one where you produced that "dual" 2. Bg2 move.  (The title bar says "Endgame.pgn").

![image](https://github.com/czbar/ChessForge/assets/7270924/b13a0660-8845-43e5-8534-a223a8a7dc5a)

**Comment by czbar** [comment] 2023-08-10 00:10
I have tried repeating all the steps in your video (importing 500 games, clicking around etc.) in attempt to reproduce the problem.

The first symptom in your video is when you click on 1...e5, and in the scoresheet in remains 1...c5 but I cannot reproduce that.

**Comment by czbar** [comment] 2023-08-10 00:32
Oh, ok, please ignore. I have a repro now!

**Comment by czbar** [comment] 2023-08-10 01:41
**Issue 2**: now fixed (will release private build 1.2.3 soon)

**Issue 3**: i.e., hiding engine lines after the user clicked on the scoresheet:  fixed as well

**Comment by akaKarthick** [comment] 2023-08-19 18:47
I guess we missed this one. https://youtu.be/IMIztYSWaWk

**Comment by czbar** [comment] 2023-08-19 22:52
Yes, fixed in the upcoming release.

**Closed** 2023-08-20 04:32 UTC
Labels: fixed
