### ISSUE TITLE
Improve bookmarking experience

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#674] opened 2023-08-19 20:35 UTC
I'm wondering if it would be possible to add an option to bookmark a position with a notification. Currently, when you click the "Bookmark this position" button in the Study/game/exercise window, it opens the bookmark window. This can be inconvenient if you just want to bookmark a position quickly and easily, without having to navigate away from the current window.

I think it would be pretty cool if we could replace opening bookmark window with a notification that pops up at the bottom of the screen, informing the user that the position has been bookmarked. The notification could be a brief message, like "Position bookmarked", and it could also be accompanied by a sound, like a bell or chime or chess related sound.

I think this would be a good way to implement the bookmark feature without taking the user away from the current window. It would allow users to bookmark positions quickly and easily, without having to interrupt their work.

Let me know what you think!

**Comment by czbar** [comment] 2023-08-19 21:37
Agreed.

**Comment by czbar** [comment] 2023-08-21 17:16
Implemented in the upcoming release 1.3.0

**Comment by akaKarthick** [comment] 2023-09-22 18:59
Currently, if a user tries to bookmark a position that is already bookmarked, the "Bookmark this position" option is still displayed. This can be annoying and confusing for users, as they may not expect to see this option if the position is already bookmarked.

I suggest that, instead of displaying the "Bookmark this position" option, we display a "Remove this bookmark" option. This would make it clear to the user that the position is already bookmarked, and give them the option to remove it if they wish.

**Comment by czbar** [comment] 2023-09-23 01:19
Good suggestion. Implemented in the next version.

**Comment by akaKarthick** [comment] 2023-10-18 18:12
1. **Customizable bookmark tiles:** The current bookmark tile size of 4x3 is too small, especially for users with visual impairments. Users should be able to customize the size and shape of the bookmark tiles to suit their preferences.

2. **Bookmark alignment:** Bookmarks should be alignable, just like games in the Chapters tab or Drag and Drop. And rethink the logic.  Beacuse  newly bookmarked position of exercise going to last page, if the user bookmarked a lot of position of study and game position.

3. Make the drop-down box text larger and more readable. 

4. **Arrows and circles in bookmarks:** If the original position has arrows and circles, these should be included in the bookmark. This would make it easier for users to understand the position at a glance.

5. **Board orientation in bookmarks:** The board orientation of bookmarked positions in the Bookmarks tab should depend on who to move(execise), the original position (Study,Game). Currently, the board orientation is always white at the bottom, which can be confusing for users.

Let me know what you think.

**Comment by czbar** [comment] 2023-10-19 04:19
**Re 1**: Not sure about proper customization of size and shape but it is certainly possible to have an option of 3x3 or 3x2 with larger diagrams.  

Generally, though, accessibility features are time-consuming to implement and, for now, I am focusing on the functionality that may make the program more popular.  In particular, I am told that the problem is the lack of Chess Forge specific content as most people want to consume content rather than create their own.  

Which is why I prioritize the Online Library and its content right now.  If, with Online Library available in the next public version, Chess Forge's user base does not grow considerably in the next few months, I may have to put the whole project on the slow burner :(   Here's the graph with download numbers (October data is not complete, of course)

![image](https://github.com/czbar/ChessForge/assets/7270924/70d25dd7-4c1f-463b-9634-269fb7a962f2)

**Re 2.**  What do you mean by "_alignable, just like games in the Chapters tab_".  Do you mean the ability to re-order them manually?

As for the automatic ordering, I have changed it a couple of times already based on feedback.  And btw it is very easy to change (just one small function that controls it). Mind you, it will become much more complicated, if we allow manual reordering and then create a new bookmark.  The program would have to honor the previous manual re-ordering and somehow apply the default logic still. Could be messy.

**Re 3.**  This I should be able to do quite easily (despite the limited space where those things have to fit).    

**Re 4.** Sounds like a good idea.  Off the top of my head I am not sure how difficult it will be but I'll take a look.
 
**Re 5.** This is another somewhat controversial topic. Most traditional books put White at the bottom regardless of whose move it is.  Chess Forge does it differently, of course, in its Study/Games/Exercise tabs. So maybe Bookmarks should follow that too. I don't know, people seem to have different preferences here.

**Comment by czbar** [comment] 2024-12-04 18:16
Review when designing a future V2.

Closing and marking for V2.

**Closed by czbar** 2024-12-04 18:16 UTC
Labels: V2 Proposal
